// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdTiJiBzUn0swYkVVOjVdhid2l5BCatrY',
    appId: '1:1019070919615:web:cddadb043f3f683bc2670a',
    messagingSenderId: '1019070919615',
    projectId: 'uasppb-30ca4',
    authDomain: 'uasppb-30ca4.firebaseapp.com',
    storageBucket: 'uasppb-30ca4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-FuW6TP2nZ7Gep2HuVIXk9EFLmdU5Qs',
    appId: '1:1019070919615:android:ba77d5b4ceccc1f2c2670a',
    messagingSenderId: '1019070919615',
    projectId: 'uasppb-30ca4',
    storageBucket: 'uasppb-30ca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfO9lCQ_rwYLH6XCmMD1WaVp1A5iydgaA',
    appId: '1:1019070919615:ios:bc23fbc77b18b680c2670a',
    messagingSenderId: '1019070919615',
    projectId: 'uasppb-30ca4',
    storageBucket: 'uasppb-30ca4.firebasestorage.app',
    iosBundleId: 'com.example.pbb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfO9lCQ_rwYLH6XCmMD1WaVp1A5iydgaA',
    appId: '1:1019070919615:ios:bc23fbc77b18b680c2670a',
    messagingSenderId: '1019070919615',
    projectId: 'uasppb-30ca4',
    storageBucket: 'uasppb-30ca4.firebasestorage.app',
    iosBundleId: 'com.example.pbb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdTiJiBzUn0swYkVVOjVdhid2l5BCatrY',
    appId: '1:1019070919615:web:3c017e3a21fbd424c2670a',
    messagingSenderId: '1019070919615',
    projectId: 'uasppb-30ca4',
    authDomain: 'uasppb-30ca4.firebaseapp.com',
    storageBucket: 'uasppb-30ca4.firebasestorage.app',
  );
}
